name: my-apache2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  DOCKER_HUB_REPO: my-apache2
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo to runner
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest
